  // RCP_CAT_PROPERTY=0,
  // RCP_CAT_CONFIGURATION,
  // RCP_CAT_STATUS,
  // RCP_CAT_INFORMATION,
  // RCP_CAT_LOGS,
  // RCP_CAT_SETTINGS,
  // NUM_CAT_TYPES

  
#include "RCP_Topics.hpp"

#ifndef RCP_CONTROLLER_HPP             		
#define RCP_CONTROLLER_HPP

#endif //RCP_CONTROLLER_TOPIC_HPP

